project:
  type: website

website:
  title: "Mike Mahoney"
  site-url: https://mm218.dev
  description: "Technology and the Environment"
  comments:
    utterances:
      repo: mikemahoney218/mm218.dev
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: "Papers"
        href: papers
      - text: "Presentations"
        href: presentations
      - text: "Blog"
        href: blog.html
      - icon: rss
        href: blog.xml
  page-footer:
    left: "Â© Copyright 2022 Mike Mahoney. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0."
format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
