[[redirects]]
  from = "/orcid"
  to = "https://orcid.org/0000-0003-2402-304X"

[[redirects]]
  from = "/github"
  to = "https://github.com/mikemahoney218"

[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/mikemahoney218/"

[[redirects]]
  from = "/researchgate"
  to = "https://www.researchgate.net/profile/Michael_Mahoney13"

[[redirects]]
  from = "/twitter"
  to = "https://www.twitter.com/mikemahoney218"

[[redirects]]
  from = "/cv"
  to = "/cv.pdf"

[[redirects]]
  from = "/resume"
  to = "/resume.pdf"

[[redirects]]
  from = "/quotes"
  to = "/quotes/index.html"

[[redirects]]
  from = "/2020/04/mechanics-of-viz"
  to = "/posts/2020/04/mechanics-of-viz"

[[redirects]]
  from = "/2020/05/tig-on-pi"
  to = "/posts/2020/05"

[[redirects]]
  from = "/2020/04/theory-of-data-viz"
  to = "/posts/2020/04/theory-of-data-viz"

[[redirects]]
  from = "/2020/04/making-excellent-viz"
  to = "/posts/2020/04/making-excellent-viz"

  [[redirects]]
  from = "/blog/2020/04/mechanics-of-viz"
  to = "/posts/2020/04/mechanics-of-viz"

[[redirects]]
  from = "/blog/2020/05/tig-on-pi"
  to = "/posts/2020/05"

[[redirects]]
  from = "/blog/2020/04/theory-of-data-viz"
  to = "/posts/2020/04/theory-of-data-viz"

[[redirects]]
  from = "/blog/2020/04/making-excellent-viz"
  to = "/posts/2020/04/making-excellent-viz"

[[redirects]]
  from = "/heddlr"
  to = "https://mikemahoney218.github.io/heddlr/"

[[redirects]]
  from = "/spacey"
  to = "https://mikemahoney218.github.io/spacey/"

[[redirects]]
  from = "/terrainr"
  to = "https://docs.ropensci.org/terrainr/"

[[redirects]]
  from = "/proceduralnames"
  to = "https://mikemahoney218.github.io/proceduralnames/"

[[redirects]]
  from = "/mvdf"
  to = "https://mikemahoney218.github.io/mvdf/"

[[redirects]]
  from = "/workshop"
  to = "https://docs.google.com/spreadsheets/d/1Nu0RFNixHfQvZcxdLe0WROPEw51TAa_9mg0CxNswAcY/edit?usp=sharing"

[[redirects]]
  from = "/esip2021"
  to = "https://mikemahoney218.github.io/2021-09-08_esip/esip.html#2"

[[redirects]]
  from = "/talks"
  to = "/presentations"

[[redirects]]
  from = "/vrs2021"
  to = "https://mikemahoney218.github.io/2021-10-21-vrs/vrs.html#2"

[[redirects]]
  from = "/vrs2021_workshop"
  to = "https://mikemahoney218.github.io/2021-10-19-vrs-workshop/2021-10-19-vrs-workshop.html"

[[redirects]]
  from = "/agu2021"
  to = "https://www.mm218.dev/papers/ground_filtering/"

[[redirects]]
  from = "/unifir"
  to = "https://docs.ropensci.org/unifir/"

[[redirects]]
  from = "/NAFEW"
  to = "https://doi.org/10.31223/X5HG99"

[[redirects]]
  from = "/ground_filtering"
  to = "https://doi.org/10.31223/X5HG99"

[[redirects]]
  from = "/user2022"
  to = "https://mikemahoney218.github.io/2022-06-22_user/slides.html"

